FROM mcr.microsoft.com/vscode/devcontainers/base:0.202.0-debian-11

# RUN apk add --update npm && \
#     npm install --global eslint && \
#     npm install --global mocha && \
#     npm install --global ls-lint && \
#     npm install --global rimraf && \
#     npm install --global rollup

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
